Repository SyncFit/server, pull requests merged in 2025-02, with the labels that each got.

#2 chore: 프로젝트 초기 세팅
  .github/ISSUE_TEMPLATE /chore.md
  .github/ISSUE_TEMPLATE /feature.md
  .github/ISSUE_TEMPLATE /fix.md
  .github/ISSUE_TEMPLATE /refactor.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ⚙️ chore

#11 feat: BaseTimeEntity 생성
  src/main/java/com/amcamp/domain/common/model/BaseTimeEntity.java
  src/main/java/com/amcamp/infra/config/jpa/JpaAuditingConfig.java
Labels: ✨ feature

#10 chore: Global Exception Handler 생성
  src/main/java/com/amcamp/error/ErrorResponse.java
  src/main/java/com/amcamp/error/GlobalExceptionHandler.java
  src/main/java/com/amcamp/error/exception/CustomException.java
  src/main/java/com/amcamp/error/exception/ErrorCode.java
  src/main/java/com/amcamp/global/common/response/GlobalResponse.java
Labels: ⚙️ chore

#14 feat: 회원 도메인 구현
  src/main/java/com/amcamp/domain/member/api/.gitkeep
  src/main/java/com/amcamp/domain/member/application/.gitkeep
  src/main/java/com/amcamp/domain/member/dao/MemberRepository.java
  src/main/java/com/amcamp/domain/member/domain/Member.java
  src/main/java/com/amcamp/domain/member/domain/MemberRole.java
  src/main/java/com/amcamp/domain/member/domain/OauthInfo.java
  src/main/java/com/amcamp/domain/member/dto/.gitkeep
Labels: ✨ feature

#16 chore: Redis 설정
  build.gradle
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/java/com/amcamp/infra/config/redis/RedisConfig.java
  src/main/java/com/amcamp/infra/config/redis/RedisProperties.java
  src/main/resources/application.yml
Labels: ⚙️ chore

#17 chore: Global Exception Handler 생성
  src/main/java/com/amcamp/global/common/response/GlobalResponse.java
  src/main/java/com/amcamp/global/error/ErrorResponse.java
  src/main/java/com/amcamp/global/error/GlobalExceptionHandler.java
  src/main/java/com/amcamp/global/error/exception/CustomException.java
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
Labels: ⚙️ chore

#19 feat: 소셜 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/amcamp/domain/auth/api/AuthController.java
  src/main/java/com/amcamp/domain/auth/application/AuthService.java
  src/main/java/com/amcamp/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/amcamp/domain/auth/application/JwtTokenService.java
  src/main/java/com/amcamp/domain/auth/application/KakaoService.java
  src/main/java/com/amcamp/domain/auth/dao/RefreshTokenRepository.java
  src/main/java/com/amcamp/domain/auth/domain/RefreshToken.java
  src/main/java/com/amcamp/domain/auth/dto/AccessTokenDto.java
  src/main/java/com/amcamp/domain/auth/dto/RefreshTokenDto.java
  src/main/java/com/amcamp/domain/auth/dto/request/AuthCodeRequest.java
  src/main/java/com/amcamp/domain/auth/dto/response/IdTokenResponse.java
  src/main/java/com/amcamp/domain/auth/dto/response/SocialLoginResponse.java
  src/main/java/com/amcamp/domain/member/dao/MemberRepository.java
  src/main/java/com/amcamp/global/config/feign/FeignConfig.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
  src/main/java/com/amcamp/global/util/CookieUtil.java
  src/main/java/com/amcamp/global/util/JwtUtil.java
  src/main/java/com/amcamp/infra/config/feign/KakaoOauthClient.java
  src/main/java/com/amcamp/infra/config/jwt/JwtProperties.java
  src/main/java/com/amcamp/infra/config/oauth/KakaoProperties.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/resources/application.yml
Labels: ✨ feature

#21 feat: 로그인한 멤버 조회 유틸리티 구현
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/global/util/MemberUtil.java
Labels: ✨ feature

#27 feat: 로그인한 회원 정보 조회
  src/main/java/com/amcamp/domain/member/api/.gitkeep
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/.gitkeep
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/main/java/com/amcamp/domain/member/dto/.gitkeep
  src/main/java/com/amcamp/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
Labels: ✨ feature

#29 feat: 로그아웃 구현
  src/main/java/com/amcamp/domain/member/api/MemberController.java
  src/main/java/com/amcamp/domain/member/application/MemberService.java
  src/main/java/com/amcamp/global/util/CookieUtil.java
Labels: ✨ feature

#33 feat: 장르 추천 기능 구현
  src/main/java/com/amcamp/domain/chat/api/ChatController.java
  src/main/java/com/amcamp/domain/chat/application/ChatService.java
  src/main/java/com/amcamp/domain/chat/application/PromptGenerator.java
  src/main/java/com/amcamp/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/amcamp/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/amcamp/domain/chat/dto/response/GenreRecommendationResponse.java
  src/main/java/com/amcamp/infra/config/chat/ChatConfig.java
  src/main/java/com/amcamp/infra/config/chat/ChatInterface.java
  src/main/java/com/amcamp/infra/config/chat/ChatProperties.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/resources/application.yml
Labels: ✨ feature

#32 chore: application.yml 환경 분리
  build.gradle
  src/main/resources/application-datasource.yml
  src/main/resources/application-dev.yml
  src/main/resources/application-gemini.yml
  src/main/resources/application-local.yml
  src/main/resources/application-redis.yml
  src/main/resources/application-security.yml
  src/main/resources/application.yml
Labels: ⚙️ chore

#36 chore: CI/CD 파이프라인 구축
  .github/workflows/develop_build_deploy.yml
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: ⚙️ chore

#39 fix: gemini profile 추가 및 workflow 일부 수정
  .github/workflows/develop_build_deploy.yml
  src/main/resources/application.yml
Labels: 🐛 bug/error

#42 fix: CORS 정책 및 JWT 토큰 필터 로직 수정
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
Labels: 🐛 bug/error

#43 feat: Spotify 곡 조회 기능 구현
  build.gradle
  src/main/java/com/amcamp/domain/spotify/api/SpotifyController.java
  src/main/java/com/amcamp/domain/spotify/application/SpotifyService.java
  src/main/java/com/amcamp/domain/spotify/dto/response/SpotifySearchResponse.java
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/java/com/amcamp/infra/config/spotify/SpotifyConfig.java
  src/main/java/com/amcamp/infra/config/spotify/SpotifyProperties.java
  src/main/resources/application-spotify.yml
  src/main/resources/application.yml
Labels: ✨ feature

#37 feat: 위시리스트 생성 구현
  src/main/java/com/amcamp/domain/wishlist/api/WishlistController.java
  src/main/java/com/amcamp/domain/wishlist/application/WishlistService.java
  src/main/java/com/amcamp/domain/wishlist/dao/WishlistRepository.java
  src/main/java/com/amcamp/domain/wishlist/domain/Wishlist.java
  src/main/java/com/amcamp/domain/wishlist/dto/request/WishlistCreateRequest.java
  src/main/java/com/amcamp/domain/wishlist/dto/response/WishlistInfoResponse.java
Labels: ✨ feature

#44 feat: 어드민 기능 구현
  src/main/java/com/amcamp/domain/admin/api/AdminController.java
  src/main/java/com/amcamp/domain/admin/application/AdminService.java
  src/main/java/com/amcamp/domain/admin/dto/response/MemberInfoResponse.java
  src/main/java/com/amcamp/global/config/security/WebSecurityConfig.java
  src/main/java/com/amcamp/global/security/JwtAuthenticationFilter.java
  src/main/java/com/amcamp/global/security/PrincipalDetails.java
Labels: ✨ feature

#46 feat: 트랙 추가, 삭제, 조회 구현
  src/main/java/com/amcamp/domain/track/api/TrackController.java
  src/main/java/com/amcamp/domain/track/application/TrackService.java
  src/main/java/com/amcamp/domain/track/dao/TrackRepository.java
  src/main/java/com/amcamp/domain/track/domain/Track.java
  src/main/java/com/amcamp/domain/track/dto/request/TrackCreateRequest.java
  src/main/java/com/amcamp/domain/track/dto/response/TrackInfoResponse.java
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
Labels: ✨ feature

#48 refactor: 트랙 추가 방식을 리스트에서 단일 트랙으로 변경
  src/main/java/com/amcamp/domain/track/api/TrackController.java
  src/main/java/com/amcamp/domain/track/application/TrackService.java
Labels: ♻️ refactor

#51 feat: YouTube 검색 기능 구현
  build.gradle
  src/main/java/com/amcamp/domain/youtube/api/YouTubeController.java
  src/main/java/com/amcamp/domain/youtube/application/YouTubeService.java
  src/main/java/com/amcamp/domain/youtube/dto/response/YouTubeVideoIdResponse.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/java/com/amcamp/infra/config/youtube/YoutubeProperties.java
  src/main/resources/application-youtube.yml
  src/main/resources/application.yml
Labels: ✨ feature

#49 feat: 이미지 관리 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/amcamp/domain/image/api/ImageController.java
  src/main/java/com/amcamp/domain/image/application/ImageService.java
  src/main/java/com/amcamp/domain/wishlist/api/WishlistController.java
  src/main/java/com/amcamp/domain/wishlist/application/WishlistService.java
  src/main/java/com/amcamp/domain/wishlist/dao/WishlistRepository.java
  src/main/java/com/amcamp/domain/wishlist/domain/Wishlist.java
  src/main/java/com/amcamp/domain/wishlist/dto/request/WishlistCreateRequest.java
  src/main/java/com/amcamp/domain/wishlist/dto/response/WishlistInfoResponse.java
  src/main/java/com/amcamp/global/common/response/GlobalResponseAdvice.java
  src/main/java/com/amcamp/global/error/exception/ErrorCode.java
  src/main/java/com/amcamp/infra/config/image/FirebaseConfig.java
  src/main/java/com/amcamp/infra/config/image/FirebaseProperties.java
  src/main/java/com/amcamp/infra/config/properties/PropertiesConfig.java
  src/main/resources/application-firebase.yml
  src/main/resources/application.yml
Labels: ✨ feature

#55 fix: 어드민 회원 삭제 기능 수정
  src/main/java/com/amcamp/domain/member/domain/Member.java
Labels: 🐛 bug/error

#62 chore: Dockerfile, Docker Compose 설정
  Dockerfile
  docker-compose.yml
  schema.sql
  src/main/java/com/amcamp/infra/config/redis/RedisConfig.java
  src/main/resources/application-datasource.yml
  src/main/resources/application-redis.yml
Labels: ⚙️ chore
